# Configuration pour PostgreSQL (Configuration par défaut)

# Base de données PostgreSQL active

spring.datasource.url=jdbc:postgresql://localhost:5432/stock_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Charger depuis CSV au démarrage
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

server.port=8080
