version: '3.8'

services:
  # Base de Données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: stock_management_db
    restart: always
    environment:
      POSTGRES_DB: stock_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/main/resources/data.sql:/docker-entrypoint-initdb.d/01-data.sql
    networks:
      - stock_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  stock_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
