spring.application.name=stock_management


spring.datasource.url= jdbc:postgresql://localhost:5432/stock_management_db
spring.datasource.username= postgres
spring.datasource.password= 123

###### Just  do for the first time
### Enables Spring to automatically execute schema.sql and data.sql on startup
#spring.sql.init.mode=always
##spring.sql.init.mode=never
#
## By default, Spring Boot looks for schema.sql and data.sql in the classpath
#spring.sql.init.schema-locations=classpath:schema.sql
#spring.sql.init.data-locations=classpath:data.sql



cors.allowedOrigins=http://localhost:8081, http://localhost:8082
